### ISSUE TITLE
能不能打个deb包？

### ISSUE THREAD

**Issue by dg1vg4** [Catty2014/osu-lazer-loongarch#1]
主要是用debian系的人比较多。

**Comment by Catty2014** [comment]
尝试着打包了一个.deb: ~~https://github.com/Catty2014/osu-lazer-loongarch/releases/tag/2024.1208.0~~ https://github.com/Catty2014/osu-lazer-loongarch/releases/tag/2024.1208.0-3

如果有问题欢迎反馈哈
